__default__:
    time: 00:30:00
    job-name:  LiftOver
    account: project_2001746
    ntasks: 1
    cpus-per-task: 1
    mem-per-cpu: 4000
    partition: small
    working-directory: /scratch/project_2001746/logs/
    nvme: 0

# Module 1- Preprocessing
################################################################################
fastp_trim_reads:
    job-name: fastp
    time: 01:00:00
    cpus-per-task: 10
