project-folder: "/scratch/project_2005222/SNPPanel"                   
pipeline-folder: "/users/fischerd/git/Snakebite-LiftOver"
pipeline-config: "Snakebite-LiftOver_config.yaml"
server-config: "Snakebite-LiftOver_server-config.yaml"
local-scratch: $LOCAL_SCRATCH
tmp-folder: "tmp"

start-genome: ""
end-genome: ""
start-bed: ""
end-bed: ""

params:
    pblat:
        threads: 30
